#%RAML 1.0
title: customer
version: v1
baseUri: http://api.samplehost.com
/customer:
  get:
    responses:
      200:
        description: Return Customer Details
        body:
          application/json:
            example: !include custProfileSample.json
            schema: !include custProfileSchema.json
  /{customer-id}:
    get:
      responses:
        200:
          description: Return Customer Details
          body:
            application/json:
              example: !include custProfileSample.json
              schema: !include custProfileSchema.json
